core/urls.py
from django.urls import path

from .views import home

urlpatterns = [
    path('', home, name='home'),
]

starter/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from users.views import profile

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('users.urls', namespace='users')),
    path('@<username>/', profile, name='profile'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
               static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import profile, profile_edit, profile_settings, profile_email_change, profile_email_verify, profile_delete

app_name = 'users'

urlpatterns = [
    path('', profile, name='profile'),
    path('edit/', profile_edit, name='profile_edit'),
    path('onboarding/', profile_edit, name='profile_onboarding'),
    path('settings/', profile_settings, name='profile_settings'),
    path('email/change/', profile_email_change, name='profile_email_change'),
    path('email/verify/', profile_email_verify, name='profile_email_verify'),
    path('delete/', profile_delete, name='profile_delete'),
]

core/models.py
from django.db import models

# Create your models here.

users/models.py
import uuid

from django.templatetags.static import static
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from .managers import UserManager
from core.utils import get_upload_path

username_validator = UnicodeUsernameValidator()


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    phone = models.CharField(_('phone'), max_length=13, unique=True, blank=True, null=True)
    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    email = models.EmailField(_('email'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'


class Profile(models.Model):
    class Sex(models.TextChoices):
        MALE = 'M', 'Male'
        FEMALE = 'F', 'Female'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    image = models.ImageField(_('image'), upload_to=get_upload_path, blank=True, null=True)
    sex = models.CharField(_('sex'), max_length=2, choices=Sex.choices, default='')
    birth_date = models.DateField(_('birth date'), blank=True, null=True)
    nickname = models.CharField(_('nickname'), max_length=20, blank=True, null=True)
    bio = models.TextField(_('biography'), max_length=150, blank=True, null=True)
    address = models.CharField(_('address'), max_length=128, blank=True, null=True)
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, verbose_name=_('user'))
    created_at = models.DateTimeField(_('created date'), auto_now_add=True)
    updated_at = models.DateTimeField(_('updated date'), auto_now=True)

    def __str__(self):
        return f'{self.user} Profile'

    @property
    def name(self):
        if self.nickname:
            name = self.nickname
        else:
            name = self.user.username
        return name

    @property
    def avatar(self):
        try:
            avatar = self.image.url
        except (FileNotFoundError, ValueError, AttributeError):
            avatar = static('images/avatar.svg')
        return avatar

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordChangeForm
from .models import User, Profile


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'phone', 'first_name', 'last_name', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='email')


class UserChangingForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'phone', 'first_name', 'last_name', 'password']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'phone', 'first_name', 'last_name']


class PasswordUpdateForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']
        widgets = {
            'image': forms.FileInput(),
            'sex': forms.Select(),
            'birth_date': forms.DateInput(attrs={'type': 'date'}),
            'nickname': forms.TextInput(attrs={'placeholder': 'Add display name'}),
            'address': forms.TextInput(attrs={'placeholder': 'Add address'}),
            'bio': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Add biography'})
        }


class EmailForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['email']

core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

users/views.py
from allauth.account.utils import send_email_confirmation
from django.contrib import messages
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from users.forms import ProfileForm, EmailForm

User = get_user_model()


def profile(request, username=None):
    if username:
        user_profile = get_object_or_404(User, username=username).profile
    else:
        try:
            user_profile = request.user.profile
        except AttributeError:
            # If the user does not have a profile, redirect to login
            return redirect('account_login')
    return render(request, 'users/profile.html', {'profile': user_profile})


@login_required
def profile_edit(request):
    form = ProfileForm(instance=request.user.profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('users:profile')

    # Default value for onboarding if not in 'POST' request
    onboarding = request.path == reverse('users:profile_onboarding')
    return render(request, 'users/profile_edit.html', {'form': form, 'onboarding': onboarding})


@login_required
def profile_settings(request):
    return render(request, 'users/profile_settings.html')


@login_required
def profile_email_change(request):
    if request.htmx:
        form = EmailForm(instance=request.user)
        return render(request, 'partials/email_form.html', {'form': form})

    if request.method == 'POST':
        form = EmailForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            # Send email confirmation
            send_email_confirmation(request, request.user)
        else:
            email = request.user.email
            if User.objects.filter(email=email).exclude(id=request.user.id).exists():
                messages.warning(request, f'{email} is already in use.')
                return redirect('users:profile_settings')

    # Redirect to profile settings page after form submission
    return redirect('users:profile_settings')


@login_required
def profile_email_verify(request):
    send_email_confirmation(request, request.user)
    return redirect('users:profile_settings')


@login_required
def profile_delete(request):
    user = request.user
    if request.method == "POST":
        logout(request)
        user.delete()
        messages.success(request, 'Account deleted, what a pity')
        return redirect('chats:home')

    return render(request, 'users/profile_delete.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
    <script src="https://unpkg.com/htmx.org/dist/htmx.js" defer></script>
    <script src="https://unpkg.com/htmx.org/dist/ext/ws.js"></script>
    <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <style type="text/tailwindcss">
        [x-cloak] { 
            display: none !important; 
        }
        h1 {
            @apply text-4xl font-bold mb-4
        }
        h2 {
            @apply text-xl font-bold mb-2
        }
        p {
            @apply mb-4
        }
        .button, button, [type='submit'], [type='button'] {
            @apply bg-indigo-600 text-white font-bold px-6 py-4 inline-block 
            rounded-lg shadow-lg transition-all cursor-pointer
        }
        .button:hover, button:hover, [type='submit']:hover, [type='button']:hover {
            @apply bg-indigo-700
        }
        .button:active, button:active, [type='submit']:active, [type='button']:active {
            @apply scale-95
        }
        .button.alert, button.alert {
            @apply bg-red-700
        }
        .button.alert:hover, button.alert:hover {
            @apply bg-red-600
        }
        .button-red {
            @apply !bg-red-500 hover:!bg-red-600
        }
        .button-gray {
            @apply !bg-gray-300 hover:!bg-[#c3c9d0]
        }
        .navitems>li>a {
            @apply flex items-center gap-2 h-12 px-4 hover:bg-gray-700 rounded-lg;
        }
        .hoverlist>* {
            @apply hover:bg-gray-100 rounded-md transition duration-150;
        }
        .hoverlist>*>a {
            @apply flex items-center p-2;
        }
        .highlight {
            @apply !bg-indigo-100;
        }
        .allauth content a {
            @apply underline underline-offset-2
        }
        .allauth content a:hover {
            @apply text-indigo-500
        }
        .allauth form[action="/accounts/signup/"] ul {
            @apply hidden
        }
        .allauth form[action="/accounts/signup/"] ul.errorlist {
            @apply block
        }
        .allauth .helptext {
            @apply block mt-4
        }
        label {
            @apply hidden
        }
        input[type=file] {
            @apply bg-white pl-0
        }
        .textarea, textarea, input {
            @apply w-full rounded-lg py-4 px-5 bg-gray-100
        }
        .errorlist li {
            @apply p-1 pl-4 border-l-red-500 border-l-4 border-solid mb-2 text-red-500
        }
        label[for="id_remember"] {
            @apply inline-block w-auto mr-2
        }
        input[name="remember"] {
            @apply w-auto
        }
        .alert-info { @apply bg-blue-300 }
        .alert-success { @apply bg-green-400 }
        .alert-warning { @apply bg-amber-400 }
        .alert-danger { @apply bg-amber-500 }
    </style>
</head>
<body class="{% block class %}{% endblock %}">
	
    {% include 'includes/messages.html' %}

    {% include 'includes/header.html' %}

    {% block layout %}
    	
    {% endblock %}

    {% block script %}
    	
    {% endblock %}

</body>
</html>

templates/home.html
{% extends 'layouts/blank.html' %}
{% block title %}Home{% endblock %}

{% block content %}
    <div class="max-w-4xl mx-auto px-8 py-24">
        <h1>New Project</h1>
    </div>
{% endblock %}

templates/includes/header.html
{% load static %}
<header class="flex items-center justify-between bg-gray-800 h-20 px-8 text-white sticky top-0 z-40">
    <div>
        <a class="flex items-center gap-2" href="/">
            <img class="h-6" src="{% static 'images/logo.svg' %}" alt="Logo"/>
            <span class="text-lg font-bold">Salt</span>
        </a>
    </div>
    <nav class="block bg-gray-800 relative">
        <ul class="navitems flex items-center justify-center h-full">
            {% if request.user.is_authenticated %}
                <li><a href="/">Home</a></li>
                <li x-data="{ dropdownOpen: false }" class="relative">
                    <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false"
                       class="cursor-pointer select-none">
                        <img class="h-8 w-8 rounded-full object-cover" src="{{ user.profile.avatar }}" alt=""/>
                        {{ user.profile.name }}
                        <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4"
                             src="https://img.icons8.com/small/32/777777/expand-arrow.png" alt=""/>
                    </a>
                    <div x-show="dropdownOpen" x-cloak
                         class="absolute right-0 bg-white text-black shadow rounded-lg w-40 p-2 z-20"
                         x-transition:enter="duration-300 ease-out"
                         x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                         x-transition:enter-end="opacity-100 translate-y-0 scale-100"
                    >
                        <ul class="hoverlist [&>li>a]:justify-end">
                            <li><a href="{% url 'users:profile' %}" hx-boost="true">My Profile</a></li>
                            <li><a href="{% url 'users:profile_edit' %}">Edit Profile</a></li>
                            <li><a href="{% url 'users:profile_settings' %}" hx-boost="true">Settings</a></li>
                            <li><a href="{% url 'account_logout' %}">Log Out</a></li>
                        </ul>
                    </div>
                </li>

            {% else %}
                <li><a href="{% url 'account_login' %}">Login</a></li>
                <li><a href="{% url 'account_signup' %}?next={% url 'users:profile_onboarding' %}" hx-boost="false">Signup</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

templates/includes/messages.html
<div>
    {% if messages %}
        <div x-data="{ showMessage: false }">
            {% for message in messages %}
                <div class="absolute left-0 right-0 max-w-xl mx-auto mt-3 px-4 z-50 ">
                    <div x-cloak
                         class="alert-{{ message.tags }} flex items-center py-3 pl-6 pr-4 bg-blue-500 text-white rounded-lg"
                         role="alert"
                         x-show="showMessage"
                         x-init="setTimeout(() => showMessage = true, 200), setTimeout(() => showMessage = false, 6000)"
                         x-transition:enter="duration-700 ease-out"
                         x-transition:enter-start="opacity-0 -translate-y-5"
                         x-transition:enter-end="opacity-100 translate-y-0"
                         x-transition:leave="duration-200 ease-in"
                         x-transition:leave-start="opacity-100 translate-y-0"
                         x-transition:leave-end="opacity-0 -translate-y-5">
                        <div>
                            <div class="text-lg">{{ message }}</div>
                        </div>
                        <div class="ml-auto cursor-pointer" @click="showMessage = false">
                            <svg fill="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                                 viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8 ml-2">
                                <path d="M6 18L18 6M6 6l12 12"></path>
                            </svg>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
</div>

templates/layouts/blank.html
{% extends 'base.html' %}
{% block title %} |Salt{% endblock %}
{% block layout %}
    <div class="block w-full">
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

templates/layouts/box.html
{% extends 'base.html' %}
{% block title %}Stater{% endblock %}

{% block layout %}
    <div class="block max-w-3xl mx-auto md:p-12">
        <div class="bg-white rounded-2xl md:drop-shadow-2xl shadow-black w-full p-8">

            {% block content %}
            {% endblock %}

        </div>
    </div>
{% endblock %}

templates/partials/email_form.html
<form action="{% url 'users:profile_email_change' %}" method="post"
      class="flex gap-2 text-black" autocomplete="off">
    {% csrf_token %}
    {% for field in form %}{{ field }}{% endfor %}
    <button class="block !bg-gray-800" type="submit">Submit</button>
</form>

<a href="{% url 'users:profile_settings' %}" hx-swap-oob="true" hx-boost="true" id="email-edit"
   class="font-medium text-blue-600 hover:underline">
    Cancel
</a>

users/templates/users/profile.html
{% extends 'layouts/blank.html' %}
{% block title %}{{ profile.name }}{% endblock %}

{% block content %}

<div class="max-w-lg mx-auto flex flex-col items-center pt-20 px-4">
    <img class="w-36 h-36 rounded-full object-cover mb-4" src="{{ profile.avatar }}"  alt="{{ profile.name }}"/>
    <div class="text-center">
        <h1>{{ profile.name }}</h1>
        <div class="text-gray-400 mb-2 -mt-3">@{{ profile.user.username }}</div>
        {% if profile.bio %}
        <div class="mt-8">{{ profile.bio|linebreaksbr }}</div>
        {% endif %}
    </div>
</div>

{% endblock %}

users/templates/users/profile_delete.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1>Delete Account</h1>
<p>Are you sure you want to delete your account?</p>

<form method='POST'>
    {% csrf_token %}
    <button type="submit" class="button-red mt-6">Yes, I want to delete my account</button>
    <a class="button button-gray ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
</form>

{% endblock %}

users/templates/users/profile_edit.html
{% extends 'layouts/box.html' %}
{% block title %}Edit Profile{% endblock %}


{% block content %}

    {% if onboarding %}
        <h1 class="mb-4">Complete your Profile</h1>
    {% else %}
        <h1 class="mb-4">Edit your Profile</h1>
    {% endif %}

    <div class="text-center flex flex-col items-center">
        <img id="avatar" class="w-36 h-36 rounded-full object-cover my-4" src="{{ user.profile.avatar }}" alt="{{ user.profile.name }}"/>
        <div class="text-center max-w-md">
            <h1 id="nickname">{{ user.profile.nickname|default:"" }}</h1>
            <div class="text-gray-400 mb-2 -mt-3">@{{ user.username }}</div>
        </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
        {% if onboarding %}
            <a class="button button-gray ml-1" href="{% url 'chats:home' %}">Skip</a>
        {% else %}
            <a class="button button-gray ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
        {% endif %}
    </form>




    <script>

        // This updates the avatar
        const fileInput = document.querySelector('input[type="file"]');

        fileInput.addEventListener('change', (event) => {
            const file = event.target.files[0];
            const image = document.querySelector('#avatar');

            if (file && file.type.includes('image')) {
                const url = URL.createObjectURL(file);
                image.src = url;
            }
        });

        // This updates the name
        const nickNameInput = document.getElementById('id_nickname');
        const nickNameOutput = document.getElementById('nickname');

        nickNameInput.addEventListener('input', (event) => {
            nickNameOutput.innerText = event.target.value;
        });

    </script>

{% endblock %}

users/templates/users/profile_settings.html
{% extends 'layouts/box.html' %}
{% block title %}Account Settings{% endblock %}

{% block content %}
    <h1 class="mb-8">Account Settings</h1>

    <table class="w-full text-sm text-left text-gray-500">
        <tbody>
        <tr>
            <th scope="row" class="pt-4 pb-1 text-base font-bold text-gray-900">
                Email address
            </th>
            <td id="email-address" class="pt-4 pb-1 px-6">
                {% if user.email %}{{ user.email }}{% else %}No Email{% endif %}
            </td>
            <td class="pt-4 pb-1 px-6">
                <a hx-get="{% url 'users:profile_email_change' %}"
                   hx-target="#email-address"
                   hx-swap="innerHTML"
                   id="email-edit" class="cursor-pointer font-medium text-blue-600 hover:underline">
                    Edit
                </a>
            </td>
        </tr>
        <tr class="border-b">
            <th scope="row" class="pb-4 font-medium text-gray-900">
            </th>
            <td class="px-6 pb-4">
                {% if user.emailaddress_set.first.verified %}
                    <span class="text-green-500">Verified</span>{% else %}
                    <span class="text-amber-500">Not verified</span>
                {% endif %}
            </td>
            <td class="px-6 pb-4">
                <a href="{% url 'users:profile_email_verify' %}" class="font-medium text-blue-600 hover:underline">
                    {% if not user.emailaddress_set.first.verified %}Verify{% endif %}
                </a>
            </td>
        </tr>

        <tr class="border-b">
            <th scope="row" class="py-4 text-base font-bold text-gray-900">
                Delete Account
            </th>
            <td class="px-6 py-4">
                Once deleted, account is gone. Forever.
            </td>
            <td class="px-6 py-4">
                <a href="{% url 'users:profile_delete' %}" class="font-medium text-red-600 hover:underline">
                    Delete
                </a>
            </td>
        </tr>
        </tbody>
    </table>

{% endblock %}